[toolchain]
channel = "nightly-2024-05-20"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = d84b9037541f45dc2c52a41d723265af211c0497

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
